### ISSUE TITLE
Support new version of CouchDB

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/kivik#14]
Current version of Kivik pulls couchdb:1.7 from the docker hub.  couchdb:3.1.1 is the latest, and currently actively supported tag.

**Comment by RussellMcOrmond** [comment]
Some important changes I've noticed so far:

* The "admin party" is gone, and the admin user needs to be set up.
* The cluster needs to be configured before it can be communicated to like previous versions.
* Anonymous access seems to be gone.  All requests need to be made with some user/password.


There is an API for configuring the cluster https://docs.couchdb.org/en/stable/setup/cluster.html#the-cluster-setup-api

When I set up Jarlsberg I launched the first time setting the COUCHDB_USER and COUCHDB_PASSWORD and then went through the wizard.  Launching without those variables just gave an error in the logs:


```
Jan 26 13:26:21 jarlsberg docker-couchdb[989]: *************************************************************
Jan 26 13:26:21 jarlsberg docker-couchdb[989]: ERROR: CouchDB 3.0+ will no longer run in "Admin Party"
Jan 26 13:26:21 jarlsberg docker-couchdb[989]:        mode. You *MUST* specify an admin user and
Jan 26 13:26:21 jarlsberg docker-couchdb[989]:        password, either via your own .ini file mapped
Jan 26 13:26:21 jarlsberg docker-couchdb[989]:        into the container at /opt/couchdb/etc/local.ini
Jan 26 13:26:21 jarlsberg docker-couchdb[989]:        or inside /opt/couchdb/etc/local.d, or with
Jan 26 13:26:21 jarlsberg docker-couchdb[989]:        "-e COUCHDB_USER=admin -e COUCHDB_PASSWORD=password"
Jan 26 13:26:21 jarlsberg docker-couchdb[989]:        to set it via "docker run".
Jan 26 13:26:21 jarlsberg docker-couchdb[989]: *************************************************************
```

I suspect Kivik will need to use both the environment variables as well as the cluster setup.


Once I set up the cluster the docker.ini looked similar to:

```
[admins]
admin = <PRIVATE>

[couchdb]
uuid = <Something Random>

[couch_httpd_auth]
secret = <PRIVATE>

[chttpd]
bind_address = 0.0.0.0
port = 5984

[cluster]
n = 1
```

**Comment by SaschaAdler** [comment]
I'm quite surprised at how quickly these views run out of memory, although I suspect the `item` view is the suspect, as it emits many more things than the other two.

I think all of the access views can be replaced by indexes.

**Comment by RussellMcOrmond** [comment]
A new feature to be aware of.  In the past we had to have cron poll views to cause indexes to be updated.  This is not how the new one works, and indexes are automatic unless they are shut off.

For views we don't want calculated everywhere we will want to set `autoupdate: false` in the design doc.  A way for that to be configured via Kivik will be needed.

https://docs.couchdb.org/en/stable/config/indexbuilds.html

**Comment by SaschaAdler** [comment]
Agreed, although I wonder for which kind of docs we'll want to set autoupdate to false, and for which we wouldn't.

**Comment by RussellMcOrmond** [comment]
The only ones I had in mind were repoanalysys* related as I want the data to be safe on multiple machines, but I'm only ever going to query the view on one.

**Comment by RussellMcOrmond** [comment]
I don't know what this means for us, but I want to point out that while there were a series of "out of memory" messages in the logs on Friday/etc, that after a while things settled and now http://jarlsberg.tor.c7a.ca:5984/_utils/#/database/collection/_design/access/_view/basic provides an answer.

**Comment by SaschaAdler** [comment]
I was trying to access the items view, back before I deleted it, I imagine.

**Comment by RussellMcOrmond** [comment]
Note that with Show and List functions no longer supported that the tests for these can be removed.  It seems that some of my own very old `tdrepo` related code still uses them.

```
russell@russell-XPS-13-7390:~/git$ find -name lists -type d 
./cihm-repomanage/couchdb/tdrepo/design/tdr/lists
./kivik/example/testdb/design/test/lists
russell@russell-XPS-13-7390:~/git$ find -name shows -type d 
./kivik/example/testdb/design/test/shows
russell@russell-XPS-13-7390:~/git$ 
```

While the docs say that lists are deprecated, I've noticed that they no longer work (See:  (IE: https://github.com/crkn-rcdr/CIHM-TDR/issues/10#issuecomment-772833564 )

**Comment by SaschaAdler** [comment]
Closed by #15. Any individual bits of new functionality can have their own issue so that I can track changes to make more easily.

**Comment by SaschaAdler** [comment]
Also, @RussellMcOrmond, I've set up [a default ini file](https://github.com/crkn-rcdr/kivik/blob/v2/src/container.ini) for inspect/test containers. We can add other config to this (by default dbs don't have anonymous access, which might be weird) but it's a start.

**Comment by SaschaAdler** [comment]
@RussellMcOrmond Is there anything we don't have an issue for already to do for this?

I'll endeavour to sort out replacing the .ini with config calls at some point.

**Comment by RussellMcOrmond** [comment]
It looks like everything we figured out during initial testing ended up in other issues.  If you are happy with it, this can be closed.
