### ISSUE TITLE
Mango index config

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/kivik#18]
See: https://docs.couchdb.org/en/stable/api/database/find.html#db-index

I'm not sure if indexes should go into individual design docs, or all in one, although I think the first probably makes more sense as it's what Fauxton expects. (If you create multiple indexes in one ddoc, you can't "trash" the indexes in the web interface.)

**Comment by RussellMcOrmond** [comment]
It seems to suggest using different design docs.  I'm assuming our idea is to use named design docs with only an index, and that way we have a known name to delete later or update/replace when needed?

**Comment by SaschaAdler** [comment]
How about we leave that up to whoever sets up the index to decide? Kivik can just allow for an `indexes` directory inside a database directory, with JSON files containing the PUT request body for each index.

**Comment by RussellMcOrmond** [comment]
When I was searching "couchdb mango query on view"  I saw some notes suggesting there were odd issues that sometimes required the index to be named.

I never did find what I was looking for, which is if it is possible to use /db/_find to look up information compiled as part of a map.

**Comment by SaschaAdler** [comment]
One other thing to note is that index design docs are in a different "language" than traditional design docs, and so there's no way to have a merged design doc with both indexes and views/updates.

And I'm pretty sure you can't use /db/_find to look things up in a traditional view map, if that's what you're asking.

**Comment by SaschaAdler** [comment]
Nothing I'll immediately look into, but:

If someone edits an index spec, and re-POSTs it to /db/_index with the same ddoc/name, does the index get updated? The response object for [POST /db/_index](https://docs.couchdb.org/en/stable/api/database/find.html#db-index) returns only `created` or `exists`.
