### ISSUE TITLE
Configuration in files

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/kivik#2]
Rather than the URL for the Couch database being on the command line, read from a config file.

Allow which database the design document is being written to be overridden (IE: Allow posting of design in "tdrepo/" to be posted to a tdrepo-test database).

**Comment by SaschaAdler** [comment]
Question:

What configuration is per-host, and what configuration is per-repo?

Let's say we have a kivik directory scheme set up with three databases: `alice`, `bob`, `charlie`.

Will there ever be a reason to only deploy `alice` and `bob` to one host, and `alice` and `charlie` to a different one?

`kivik.json` could look like

``` json
{
  "include": ["alice","bob","charlie"],
  "deploy": {
    "local": {
      "url": "http://localhost:5984"
    },
    "staging": {
       "url": "http://production:5984",
       "suffix": "staging"
    },
    "production": {
      "url": "http://production:5984",
      "exclude": ["bob"]
    }
  }
}
```

although if we don't need to do a per-deploy `include` or `exclude` list, we could just not do that.

**Comment by RussellMcOrmond** [comment]
Interesting -- I was being boring and primarily thinking about the username:password for authentication, which is the per-host thing.  Unless you wanted to pre-parse `url` to pull our the username:password for the new library, you'll want a place to configure that separate from `url` .

**Comment by SaschaAdler** [comment]
Right, that will be separate from `url`.

How about:

``` json
{
  "include":[] // list or glob of directories to parse as databases. default: every directory
  "exclude":[] // list or glob of directories to ignore. default: empty
  "designFiles": [] // glob patterns of files to include/exclude when in design doc subdirectories. Default: ["*.js", "!*.test.js"]
  "deploy": [
    {
      "deploy-name": { // used in "kivik deploy deploy-name"
        "url": "http://couch:5984",
        "user": "admin",
        "password": "password",
        "fixtures": false // set to true to deploy fixtures
      }
    }
  ]
}
```

I'm not sure what else to add for other modes. Validate needs some thinking, especially if we want to validate an entire database at once.
