### ISSUE TITLE
Avoid design doc overwrites when unnecessary

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/kivik#20]
More of a provisional thing than something we need to get right immediately, but I think it would be nice.

Kivik should determine, before deploying a design doc, whether or not anything about that design doc has changed. This way, we can avoid re-indexing that doesn't actually change anything.

**Comment by RussellMcOrmond** [comment]
Is this beyond the MD5 hashes?  Is this something that is different with indexes from views where CouchDB notices if there was a change?

**Comment by SaschaAdler** [comment]
Oh, hey, CouchDB already does this? That's pretty cool.
