### ISSUE TITLE
Switch kivik validate arg order

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/kivik#43]
I'd like to switch `kivik validate <document> <database>` to `kivik validate <database> <document>`, both because it matches the library behaviour and because if we ever do #9 it might make more sense.

It doesn't hurt that now that the schema is referred to by database and not by file path, `<document>` tends to be much longer than `<database>`.

**Comment by RussellMcOrmond** [comment]
I think there is a bracket or something missing in the description above before ", both because" :-)

**Comment by SaschaAdler** [comment]
Ha, yeah. Should be fixed.
