### ISSUE TITLE
Ignore editor files in path...

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/kivik#7]
I use emacs, and it creates temporary files with "~" at the end of the name.  When those files are in the directory Kivik will deploy them (meaning, deploy the previous version of the file).

```
russell@russell-XPS-13-9370:~/git/Digital-Preservation/RepositoryAnalysis/tools$ rm couchdb/repoanalysis/design/ra/updates/create_or_update.js~ 
russell@russell-XPS-13-9370:~/git/Digital-Preservation/RepositoryAnalysis/tools$ kivik deploy couchdb/ --server http://10.200.1.58:5984/
```

**Comment by SaschaAdler** [comment]
I think the above commit sorts this out; let me know if it doesn't.
