### ISSUE TITLE
Expand kivik validate to validate entire database

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/kivik#9]
It would be great to have an option to point at a CouchDB database and walk and validate the documents in the database.

IE: kivik validatedb http://iris.tor.c7a.ca:5984/manifest Databases/manifest/schema.json

This would need to page through /_all_docs , skipping design documents.

One possible output could be a JSON or other machine parse-able list of invalid document IDs accompanied by invalidity messages.

**Comment by SaschaAdler** [comment]
I suppose this would now work as `kivik validatedb http://couch/db manifest`, since `kivik validate` no longer requires a particular schema file. (See #23, #26)
